name: explora
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.13.5
  firebase_storage: ^11.6.6
  image_picker: ^1.0.7
  firebase_core_web: ^2.14.0
  firebase_auth_web: ^5.8.13
  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^6.0.0
  sign_in_with_apple: ^4.0.0
  firebase_ui_auth: ^1.10.0
  supabase_flutter: ^1.10.0
  path: ^1.8.3
  uuid: ^4.0.0
  appwrite: ^15.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/
    - assets/pink.png

